// <auto-generated />
using DotNetPOC.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DotNetPOC.Migrations.Auth
{
    [DbContext(typeof(AuthContext))]
    partial class AuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetPOC.Models.AppStatus", b =>
                {
                    b.Property<int>("AppStatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActualProgramGroupId");

                    b.HasKey("AppStatusId");

                    b.ToTable("AppStatus");
                });

            modelBuilder.Entity("DotNetPOC.Models.ProgramGroup", b =>
                {
                    b.Property<int>("ProgramGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Actual");

                    b.Property<string>("ConnectionStringKey");

                    b.Property<DateTime>("CreatedAt");

                    b.HasKey("ProgramGroupId");

                    b.ToTable("ProgramGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
